export const FETCH_USER__REQUEST = 'FETCH_USER__REQUEST';
export const FETCH_USER__SUCCESS = 'FETCH_USER__SUCCESS';
export const CURRENT_USER_REQUEST = 'CURRENT_USER_REQUEST';
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const EXIT_ACCOUNT_REQUEST = 'EXIT_ACCOUNT_REQUEST';
export const EXIT_ACCOUNT_SUCCESS = 'EXIT_ACCOUNT_SUCCESS';

